name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag image
    - name: Another way of running the Script
      run: docker run image python app.py -a "${{ secrets.API_KEY }}"
    - name: Print head git commit message
      run: |
        echo "$(git show -s --format=%s)" 
        echo "${{ github.event.pull_request.head.sha }}"